### PR TITLE
MythMusic: handle streams that repeat same metadata in changing strings

### LINKED ISSUE #790: MythMusic: radio stream history can be spammed by repeated metadata
@jpilk just mentioned in unrelated #771 that some broadcasters apparently repeat identical metadata every second.  I find this unexpected (I expect the metadata only on track change) but perhaps we could handle this better.  Currently a stream like this wedges full-screen visualizer such that it can't be exited since it is constantly overlaying the trackinfo_popup.

* **MythTV version**: fixes/33 and master

* **Component**: mythmusic radio stream

### What steps will reproduce the bug?

Add a stream to this URL: http://ice-sov.musicradio.com/ClassicFMMP3 then play it.  Notice track updates every second!  Menu -> Fullscreen Visualizer.  Escape to exit fails.

### How often does it reproduce? Is there a required condition?

always

### What is the expected behaviour?

Probably we should ignore the stream metadata if it is identical to previous data.  We should accept the data only when it changes.  That should yield just one track change notice and correct track length for a stream like this.

### What do you see instead?

Current track listed every second!

### PR DESCRIPTION
**Pull request by twitham1**
Fixes #790 by parsing the changed metadata string and accepting it only if title/artist/album changed.

The LOG of raw data string and its parse is moved to DEBUG level so that stations repeating the same StreamTitle in a changing string don't spam an INFO log.  Actual changes to StreamTitle are still logged to INFO as before only at first detection of the change.

- [x] contribution does not duplicate one of our [existing pull requests](https://github.com/MythTV/mythtv/pulls)
- [x] contribution is in a branch rebased against [master](https://github.com/MythTV/mythtv)
- [x] code compiles successfully without errors
- [x] code follows the [MythTV Coding Standards](https://www.mythtv.org/wiki/Coding_Standards)
- [x] commits are logically organised and have [good commit messages](https://chris.beams.io/posts/git-commit)

### CODE REVIEW

**Comment by Jpilk** [comment]
Thanks for this.  FYI I had git problems after Gary updated his build script and my efforts have not yet improved matters; so at present I can't comment.

File: mythplugins/mythmusic/mythmusic/avfdecoder.cpp [hunk 1]
```diff
@@ -553,27 +554,32 @@ void avfDecoder::checkMetatdata(void)
...
+            if (m_lastMetadataParsed != parsed)
+            {
+                m_lastMetadataParsed = parsed;
 
-            MusicMetadata mdata =  gPlayer->getDecoderHandler()->getMetadata();
-            mdata.setTitle(meta_map["title"]);
-            mdata.setArtist(meta_map["artist"]);
-            mdata.setAlbum(meta_map["album"]);
-            mdata.setLength(-1ms);
+                LOG(VB_PLAYBACK, LOG_INFO, QString("avfDecoder: shoutcast metadata changed - %1").arg(shout));
```
Comment (linuxdude42) [inline mythplugins/mythmusic/mythmusic/avfdecoder.cpp:571]: You have two log messages, but only print them if both conditions (line 559 and line 567) are true.
Would it make sense to leave this message at line 562 (maybe at the LOG_DEBUG level), so that when debugging you can distinguish between "new" metadata arriving, and the new metadata parsing differently than before? Otherwise, this and the subsequent message seem redundant.

Comment (linuxdude42) [reply mythplugins/mythmusic/mythmusic/avfdecoder.cpp:571]: Another argument for moving it back is that the current code prints this message before printing the two messages from parse.parseMeta.  With this change it prints after.

Comment (twitham1) [reply mythplugins/mythmusic/mythmusic/avfdecoder.cpp:571]: Your suggestion would work for most streams.  But for a verbose one like found in this bug report, line 562 runs once per second due to the changing timestamp outside the title in the shout string.  So I can only afford to report INFO level after the parse and line 567 condition to report it only once at the title change.  I like to see the raw data and parsed result even at INFO level, as in v33.

Line 564 hands off to the parse which reports the original raw and parsed only at the DEBUG level.  This way you can see the once per second raw data in DEBUG mode for a verbose stream like this one.

**Comment by Jpilk** [comment]
I'm back now with master plus these 2 PRs.  visualisers with radio streams seem fine now.  Maybe it would be better to show track info immediately on going to full-screen mode, but that might get to seem intrusive.

**Comment by twitham1** [comment]
> Maybe it would be better to show track info immediately on going to full-screen mode, but that might get to seem intrusive.

This might be optional since we just came from a screen that showed what is playing.  User can hit INFO anytime he wants a reminder.

But I have thought that hitting keys like NEXTTRACK, FFWD or SPEEDUP should probably show the trackinfo so that you can see what you are doing.  Currently you must hit INFO first if you wish to see, otherwise you are operating in the blind.  Checking on video playback, skipping ahead or going FFWD does pop the OSD and progress bar, so I think we should do this here as well.
